---
- hosts: localhost
  tasks:
    - name: Stop and remove existing container if it exists
      shell: docker rm -f calculator-app || true

    - name: Pull the latest image from Docker Hub
      shell: docker pull mt2025008/calculator:v1

    - name: Run the new container
      shell: docker run -it -a --name calculator-app mt2025008/calculator:v1