---
- hosts: localhost
  tasks:
    - name: Stop and remove existing container if it exists
      shell: sudo docker rm -f calculator-app || true

    - name: Pull the latest image from Docker Hub
      shell: sudo docker pull mt2025008/calculator:v1

    - name: Run the calculator container
      shell: sudo docker run -d --name calculator-app mt2025008/calculator:v1